### ISSUE TITLE
BUG: `pm.sample(nuts_sampler="blackjax")` fails during warmup with every blackjax >= 1.6

### ISSUE THREAD

**Issue by janfb** [pymc-devs/pymc3#8367]
### Describe the issue:

`pm.sample(nuts_sampler="blackjax")` fails during warmup with every blackjax >= 1.6, in all configurations, on all pymc versions (verified on 5.27.1 and 6.1.0).

Root cause: blackjax 1.6 removed the `progress_bar` parameter from `blackjax.window_adaptation` (progress bars moved to a context manager, `with blackjax.progress_bar(): warmup.run(...)`), and `window_adaptation` now forwards unknown `**extra_parameters` into the NUTS kernel. pymc unconditionally injects `progress_bar` into the sampler kwargs (`nuts_kwargs["progress_bar"] = progressbar`, `pymc/sampling/jax.py:359` in 6.1.0) and `_blackjax_inference_loop` only pops it *after* `blackjax.window_adaptation(**adaptation_kwargs)` has already been called (`pymc/sampling/jax.py:277` vs the `window_adaptation` call above it). The stale kwarg therefore reaches the blackjax NUTS kernel and raises during the first adaptation step.

A fix would be to pop `progress_bar` from `adaptation_kwargs` before calling `window_adaptation` and, for blackjax >= 1.6, use the new context-manager API (or drop the flag).

### Reproduceable code example:

```python
# pip install "pymc==6.1.0" "blackjax==1.6"  (also fails with pymc 5.27.1 + blackjax 1.6)
import numpy as np
import pymc as pm

with pm.Model():
    x = pm.Normal("x", 0.0, 1.0)
    pm.Normal("obs", x, 1.0, observed=np.array([0.3, -0.1, 0.5]))
    idata = pm.sample(
        draws=50, tune=50, chains=1,
        nuts_sampler="blackjax",
        progressbar=False,
    )
```

### Error message:

```shell
TypeError: build_kernel.<locals>.kernel() got an unexpected keyword argument 'progress_bar'


(raised from `blackjax/adaptation/window_adaptation.py` during `adapt.run`, wrapped by JAX tracing frames)
```

### PyMC version information:

pymc 5.27.1 and 6.1.0, blackjax 1.6, jax 0.10.x, Python 3.12, macOS (arm64) and Linux. Works with blackjax <= 1.5 (whose `window_adaptation` still accepted `progress_bar`).

**Comment by laishettikarthik-tech** [comment]
I'd like to take this on — your root-cause analysis was exactly right.
Reproduced the TypeError against current main, and confirmed a second
break behind it once that's fixed: blackjax.progress_bar.gen_scan_fn no
longer exists in >= 1.6 (progress_bar is now a context manager that
monkeypatches jax.lax.scan). Implemented a version-compatible fix
(hasattr check on gen_scan_fn, falling back to the context-manager API)
and verified the exact repro from this issue runs to completion with
both progressbar=True and False, against blackjax 1.6.2.

One thing worth flagging: with the new context-manager API, I saw a
UserWarning about no scan steps being observed in some cases, likely
from JIT-cache interaction with the outer jax.pmap — sampling still
completes correctly, but the visual bar may not always render. That
matches a caveat documented in blackjax's own progress_bar docstring
about jit-cache staleness. Happy to discuss whether that's acceptable
or needs further work before merging.
